"""creating tables

Revision ID: c02d76862dbf
Revises: 
Create Date: 2023-09-04 12:01:55.022767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02d76862dbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendancedate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_index(op.f('ix_attendancedate_id'), 'attendancedate', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_test_paaed', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('vpnuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vpnuser_email'), 'vpnuser', ['email'], unique=True)
    op.create_index(op.f('ix_vpnuser_id'), 'vpnuser', ['id'], unique=False)
    op.create_index(op.f('ix_vpnuser_ip'), 'vpnuser', ['ip'], unique=True)
    op.create_index(op.f('ix_vpnuser_username'), 'vpnuser', ['username'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vpn_user_id', sa.Integer(), nullable=True),
    sa.Column('date_id', sa.Integer(), nullable=True),
    sa.Column('first_connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('total_up_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['attendancedate.id'], ),
    sa.ForeignKeyConstraint(['vpn_user_id'], ['vpnuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_vpnuser_username'), table_name='vpnuser')
    op.drop_index(op.f('ix_vpnuser_ip'), table_name='vpnuser')
    op.drop_index(op.f('ix_vpnuser_id'), table_name='vpnuser')
    op.drop_index(op.f('ix_vpnuser_email'), table_name='vpnuser')
    op.drop_table('vpnuser')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_attendancedate_id'), table_name='attendancedate')
    op.drop_table('attendancedate')
    # ### end Alembic commands ###
